name: Bar Action

description: Echoes Hello followed by the world input.

inputs:
  world:
    description: The world to greet
    default: world

runs:
  using: composite
  steps:
    - name: Echo "Hello ${{ inputs.world }}"
      shell: bash
      run: echo "Hello ${{ inputs.world }}"
